name: never_surf_alone
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts:
  http: ^0.13.5 
  firebase_auth: ^4.2.10
  cloud_firestore: ^4.4.5
  twilio_flutter: ^0.0.9
  flutter_typeahead: ^4.3.7
  get: ^4.6.5
  geolocator: ^9.0.2
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  awesome_snackbar_content: ^0.1.2
  google_api_headers: ^1.5.0+1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  google_maps_flutter: ^2.2.3
  location: ^4.4.0 
  firebase_core: ^2.7.1 
  firebase_database: ^10.0.15

flutter:

  uses-material-design: true
  assets:
    - assets/images/logo.png

    

